baseURL = 'https://drasyl.org/'
languageCode = 'en-us'
title = 'drasyl is a high-performance framework for rapid development of distributed applications'
theme = 'Arsha'
disableKinds = ['taxonomyTerm']
pluralizeListTitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
  images = ['img/drasyl-og.png']
