baseURL = 'https://drasyl.org/'
languageCode = 'en-us'
title = 'drasyl - The Overlay Network Framework for Rapid Development of Distributed P2P Applications'
theme = 'Arsha'
disableKinds = ['taxonomyTerm']
pluralizeListTitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
  images = ['img/drasyl-og.png']