baseURL = 'https://drasyl.org/'
languageCode = 'en-us'
title = 'drasyl provides secure, software-defined overlay networks, connecting all your devices'
theme = 'Arsha'
disableKinds = ['taxonomyTerm']
pluralizeListTitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
  images = ['img/drasyl-og.png']
