baseURL = 'https://netsody.io/'
languageCode = 'en-us'
title = 'Netsody provides secure, software-defined overlay networks, connecting all your devices'
theme = 'Arsha'
disableKinds = ['taxonomyTerm']
pluralizeListTitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
  images = ['img/Netsody-og.png']
